/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectjavaapp;

import java.awt.Color;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.TableModel;
import static projectjavaapp.LibForm.dateForm;
import static projectjavaapp.LoginForm.queryToSend;
/**
 *
 * @author CLEVO
 */
public class AdmForm extends javax.swing.JFrame {
    
    static String emailUser = null;

    /**
     * Creates new form AdmForm
     * @param emailUser
     */
    public AdmForm(String emailUser) {
        AdmForm.emailUser = emailUser;
        initComponents();
        initialInit();
    }

    public void searchTable(String sear, String text, String que, JTable table){
    if(sear.trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Pole do wyszukiwania jest puste.","Uzupelnij puste pole",2);
        }
        else{
            queryToSend.add(que);
            queryToSend.add(text);
            queryToSend.add(sear);
            
            Client.readWriteServer(this, queryToSend, table, null);
        }
    }
    
    public void sendLog(String logInfo, JTextArea textArea){
                    LocalDateTime date = LocalDateTime.now();
                    queryToSend.add("60");      //sendLog
                    queryToSend.add(date.format(dateForm));
                    queryToSend.add(logInfo);
                     if(Client.readWriteServer(this, queryToSend, null, null) == 1){
                         textArea.append(date.format(dateForm) + ": " + logInfo + "\n");
                     }
                }
    
    public void clearAllFields(){
        jTextFieldImieBA.setText("");
        jTextFieldINazwiskoBA.setText("");
        jTextFieldITelefonBA.setText("");
        jTextFieldIEmailBA.setText("");
        
        jTextFieldStatBA.setText("");
    }
    
    private void initialInit(){
        jTextFieldEmailBA.setText(emailUser);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEmailBA = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTabbedPanelAdministrator = new javax.swing.JTabbedPane();
        jPanelAutorzy = new javax.swing.JPanel();
        jPanelMenuK6 = new javax.swing.JPanel();
        jLabelImieBA = new javax.swing.JLabel();
        jTextFieldImieBA = new javax.swing.JTextField();
        jLabelNazwiskoBA = new javax.swing.JLabel();
        jLabelTelefonBA = new javax.swing.JLabel();
        jButtonUsunBA = new javax.swing.JButton();
        jButtonTelefonBA = new javax.swing.JButton();
        jButtonNazwiskoBA = new javax.swing.JButton();
        jButtonImieBA = new javax.swing.JButton();
        jButtonEmailBA = new javax.swing.JButton();
        jLabelEmailBA = new javax.swing.JLabel();
        jTextFieldINazwiskoBA = new javax.swing.JTextField();
        jTextFieldITelefonBA = new javax.swing.JTextField();
        jTextFieldIEmailBA = new javax.swing.JTextField();
        jButtonUDodajBA = new javax.swing.JButton();
        jLabelEmailBA1 = new javax.swing.JLabel();
        jTextFieldStatBA = new javax.swing.JTextField();
        jPanelConsoleK = new javax.swing.JPanel();
        jScrollPaneDB_Console8 = new javax.swing.JScrollPane();
        jTextAreaBA = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelMenuBBA = new javax.swing.JPanel();
        jButtonWyswielBA1 = new javax.swing.JButton();
        jScrollPaneTableB6 = new javax.swing.JScrollPane();
        jTableBibliotekarzeBA = new javax.swing.JTable();
        jPanelMenuCBA = new javax.swing.JPanel();
        jButtonWyswielBA2 = new javax.swing.JButton();
        jScrollPaneTableB7 = new javax.swing.JScrollPane();
        jTableUzytkownicyBA = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanelSubmenuCz1 = new javax.swing.JPanel();
        jButtonOdsiezBA = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPaneTableB = new javax.swing.JScrollPane();
        jTableLogsBA = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("zalogowany jako: ");

        jTextFieldEmailBA.setEditable(false);
        jTextFieldEmailBA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldEmailBA.setBorder(null);
        jTextFieldEmailBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailBAActionPerformed(evt);
            }
        });

        jButton3.setText("WYLOGUJ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEmailBA, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEmailBA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jTabbedPanelAdministrator.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPanelAdministrator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPanelAdministratorMouseClicked(evt);
            }
        });

        jPanelMenuK6.setBorder(javax.swing.BorderFactory.createTitledBorder("Dodaj/Usuń"));

        jLabelImieBA.setText("Imię");

        jTextFieldImieBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldImieBAActionPerformed(evt);
            }
        });

        jLabelNazwiskoBA.setText("Nazwisko");

        jLabelTelefonBA.setText("Telefon");

        jButtonUsunBA.setText("USUŃ");
        jButtonUsunBA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonUsunBAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonUsunBAMouseExited(evt);
            }
        });
        jButtonUsunBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsunBAActionPerformed(evt);
            }
        });

        jButtonTelefonBA.setText("jButton1");
        jButtonTelefonBA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonTelefonBAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonTelefonBAMouseExited(evt);
            }
        });
        jButtonTelefonBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTelefonBAActionPerformed(evt);
            }
        });

        jButtonNazwiskoBA.setText("jButton1");
        jButtonNazwiskoBA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonNazwiskoBAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonNazwiskoBAMouseExited(evt);
            }
        });
        jButtonNazwiskoBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNazwiskoBAActionPerformed(evt);
            }
        });

        jButtonImieBA.setText("jButton1");
        jButtonImieBA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonImieBAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonImieBAMouseExited(evt);
            }
        });
        jButtonImieBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImieBAActionPerformed(evt);
            }
        });

        jButtonEmailBA.setText("jButton1");
        jButtonEmailBA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonEmailBAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonEmailBAMouseExited(evt);
            }
        });
        jButtonEmailBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmailBAActionPerformed(evt);
            }
        });

        jLabelEmailBA.setText("Email");

        jTextFieldINazwiskoBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldINazwiskoBAActionPerformed(evt);
            }
        });

        jTextFieldITelefonBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldITelefonBAActionPerformed(evt);
            }
        });

        jTextFieldIEmailBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIEmailBAActionPerformed(evt);
            }
        });

        jButtonUDodajBA.setText("DODAJ");
        jButtonUDodajBA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonUDodajBAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonUDodajBAMouseExited(evt);
            }
        });
        jButtonUDodajBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUDodajBAActionPerformed(evt);
            }
        });

        jLabelEmailBA1.setText("Status");

        jTextFieldStatBA.setEditable(false);
        jTextFieldStatBA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldStatBA.setBorder(null);
        jTextFieldStatBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStatBAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuK6Layout = new javax.swing.GroupLayout(jPanelMenuK6);
        jPanelMenuK6.setLayout(jPanelMenuK6Layout);
        jPanelMenuK6Layout.setHorizontalGroup(
            jPanelMenuK6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuK6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenuK6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuK6Layout.createSequentialGroup()
                        .addComponent(jButtonUDodajBA, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUsunBA, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMenuK6Layout.createSequentialGroup()
                        .addGroup(jPanelMenuK6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelEmailBA1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelImieBA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNazwiskoBA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(jLabelTelefonBA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelEmailBA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanelMenuK6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelMenuK6Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanelMenuK6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldImieBA, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(jTextFieldINazwiskoBA)
                                    .addComponent(jTextFieldITelefonBA)
                                    .addComponent(jTextFieldIEmailBA)))
                            .addGroup(jPanelMenuK6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldStatBA)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelMenuK6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonNazwiskoBA, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonTelefonBA, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEmailBA, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonImieBA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelMenuK6Layout.setVerticalGroup(
            jPanelMenuK6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuK6Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanelMenuK6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelImieBA)
                    .addComponent(jTextFieldImieBA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonImieBA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMenuK6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNazwiskoBA)
                    .addComponent(jButtonNazwiskoBA)
                    .addComponent(jTextFieldINazwiskoBA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMenuK6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefonBA)
                    .addComponent(jButtonTelefonBA)
                    .addComponent(jTextFieldITelefonBA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMenuK6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmailBA)
                    .addComponent(jButtonEmailBA)
                    .addComponent(jTextFieldIEmailBA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMenuK6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmailBA1)
                    .addComponent(jTextFieldStatBA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMenuK6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonUDodajBA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuK6Layout.createSequentialGroup()
                        .addComponent(jButtonUsunBA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanelConsoleK.setBorder(javax.swing.BorderFactory.createTitledBorder("DB Console"));

        jTextAreaBA.setEditable(false);
        jTextAreaBA.setColumns(20);
        jTextAreaBA.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jTextAreaBA.setRows(5);
        jTextAreaBA.setToolTipText("");
        jTextAreaBA.setDoubleBuffered(true);
        jScrollPaneDB_Console8.setViewportView(jTextAreaBA);

        javax.swing.GroupLayout jPanelConsoleKLayout = new javax.swing.GroupLayout(jPanelConsoleK);
        jPanelConsoleK.setLayout(jPanelConsoleKLayout);
        jPanelConsoleKLayout.setHorizontalGroup(
            jPanelConsoleKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneDB_Console8)
        );
        jPanelConsoleKLayout.setVerticalGroup(
            jPanelConsoleKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneDB_Console8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
        );

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseEntered(evt);
            }
        });
        jTabbedPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTabbedPane1ComponentShown(evt);
            }
        });

        jPanelMenuBBA.setBorder(javax.swing.BorderFactory.createTitledBorder("Szukaj"));
        jPanelMenuBBA.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanelMenuBBAComponentShown(evt);
            }
        });

        jButtonWyswielBA1.setText("W. WSZYSTKICH");
        jButtonWyswielBA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWyswielBA1ActionPerformed(evt);
            }
        });

        jTableBibliotekarzeBA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numer ID", "Imię", "Nazwisko", "Data urodzenia", "Płeć", "Telefon", "Email"
            }
        ));
        jTableBibliotekarzeBA.setToolTipText("");
        jTableBibliotekarzeBA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBibliotekarzeBAMouseClicked(evt);
            }
        });
        jScrollPaneTableB6.setViewportView(jTableBibliotekarzeBA);

        javax.swing.GroupLayout jPanelMenuBBALayout = new javax.swing.GroupLayout(jPanelMenuBBA);
        jPanelMenuBBA.setLayout(jPanelMenuBBALayout);
        jPanelMenuBBALayout.setHorizontalGroup(
            jPanelMenuBBALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneTableB6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
            .addGroup(jPanelMenuBBALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonWyswielBA1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMenuBBALayout.setVerticalGroup(
            jPanelMenuBBALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuBBALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonWyswielBA1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(jScrollPaneTableB6, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Bibliotekarze", jPanelMenuBBA);

        jPanelMenuCBA.setBorder(javax.swing.BorderFactory.createTitledBorder("Szukaj"));
        jPanelMenuCBA.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanelMenuCBAComponentShown(evt);
            }
        });

        jButtonWyswielBA2.setText("W. WSZYSTKICH");
        jButtonWyswielBA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWyswielBA2ActionPerformed(evt);
            }
        });

        jTableUzytkownicyBA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numer ID", "Imię", "Nazwisko", "Data urodzenia", "Płeć", "Telefon", "Email"
            }
        ));
        jTableUzytkownicyBA.setToolTipText("");
        jTableUzytkownicyBA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUzytkownicyBAMouseClicked(evt);
            }
        });
        jScrollPaneTableB7.setViewportView(jTableUzytkownicyBA);

        javax.swing.GroupLayout jPanelMenuCBALayout = new javax.swing.GroupLayout(jPanelMenuCBA);
        jPanelMenuCBA.setLayout(jPanelMenuCBALayout);
        jPanelMenuCBALayout.setHorizontalGroup(
            jPanelMenuCBALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneTableB7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
            .addGroup(jPanelMenuCBALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonWyswielBA2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMenuCBALayout.setVerticalGroup(
            jPanelMenuCBALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuCBALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonWyswielBA2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPaneTableB7, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Użytkownicy", jPanelMenuCBA);

        javax.swing.GroupLayout jPanelAutorzyLayout = new javax.swing.GroupLayout(jPanelAutorzy);
        jPanelAutorzy.setLayout(jPanelAutorzyLayout);
        jPanelAutorzyLayout.setHorizontalGroup(
            jPanelAutorzyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAutorzyLayout.createSequentialGroup()
                .addGroup(jPanelAutorzyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelMenuK6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelConsoleK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );
        jPanelAutorzyLayout.setVerticalGroup(
            jPanelAutorzyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAutorzyLayout.createSequentialGroup()
                .addComponent(jPanelMenuK6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelConsoleK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jTabbedPane1)
        );

        jTabbedPanelAdministrator.addTab("Bibliotekarze", jPanelAutorzy);

        jPanelSubmenuCz1.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu"));
        jPanelSubmenuCz1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanelSubmenuCz1ComponentShown(evt);
            }
        });

        jButtonOdsiezBA.setText("ODŚWIEŻ");
        jButtonOdsiezBA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonOdsiezBAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonOdsiezBAMouseExited(evt);
            }
        });
        jButtonOdsiezBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdsiezBAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSubmenuCz1Layout = new javax.swing.GroupLayout(jPanelSubmenuCz1);
        jPanelSubmenuCz1.setLayout(jPanelSubmenuCz1Layout);
        jPanelSubmenuCz1Layout.setHorizontalGroup(
            jPanelSubmenuCz1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSubmenuCz1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonOdsiezBA, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(719, 719, 719))
        );
        jPanelSubmenuCz1Layout.setVerticalGroup(
            jPanelSubmenuCz1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSubmenuCz1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonOdsiezBA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTableLogsBA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Informacje"
            }
        ));
        jTableLogsBA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLogsBAMouseClicked(evt);
            }
        });
        jScrollPaneTableB.setViewportView(jTableLogsBA);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneTableB)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneTableB, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSubmenuCz1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanelSubmenuCz1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPanelAdministrator.addTab("Informacje z serwera", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPanelAdministrator)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPanelAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEmailBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailBAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailBAActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        queryToSend.add("Exit");
        if(Client.readWriteServer(this, queryToSend, null, null) == 1){
            LoginForm form = new LoginForm();
            form.setVisible(true);
            form.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTabbedPanelAdministratorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPanelAdministratorMouseClicked
        // TODO add your handling code here:
        queryToSend.add("61");

        Client.readWriteServer(this, queryToSend, jTableLogsBA, null);
    }//GEN-LAST:event_jTabbedPanelAdministratorMouseClicked

    private void jTextFieldStatBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStatBAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStatBAActionPerformed

    private void jButtonUDodajBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUDodajBAActionPerformed
        // TODO add your handling code here:
        String email = jTextFieldIEmailBA.getText().replaceAll("\\s+","");

        if(email.trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Wymagane pole jest puste","Uzupełnij puste pole",2);
        }else{

            queryToSend.add("40");                  //checkDateAutor
            queryToSend.add(email);

            int checkId = Client.readWriteServer(this, queryToSend, null, null);
            System.out.println(checkId);
            if(checkId > 0){
                System.out.println("jest");
                queryToSend.add("56");              //checkDateAutor
                queryToSend.add(String.valueOf(checkId)); //4

                if(Client.readWriteServer(this, queryToSend, null, null) == 1){
                    String logInfo = "Administrator[ " + emailUser + "] dodal bibliotekarza z emailem: [" + email + "]";
                    sendLog(logInfo, jTextAreaBA);

                    queryToSend.add("35");
                    Client.readWriteServer(this, queryToSend, jTableUzytkownicyBA, null);
                }else{
                    System.out.println("nie ma takiego uzytkownika");
                }
            }
        }
    }//GEN-LAST:event_jButtonUDodajBAActionPerformed

    private void jButtonUDodajBAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUDodajBAMouseExited
        // TODO add your handling code here:
        jTextFieldIEmailBA.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButtonUDodajBAMouseExited

    private void jButtonUDodajBAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUDodajBAMouseEntered
        // TODO add your handling code here:
        jTextFieldIEmailBA.setBackground(LibForm.newBlue);
    }//GEN-LAST:event_jButtonUDodajBAMouseEntered

    private void jTextFieldIEmailBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIEmailBAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIEmailBAActionPerformed

    private void jTextFieldITelefonBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldITelefonBAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldITelefonBAActionPerformed

    private void jTextFieldINazwiskoBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldINazwiskoBAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldINazwiskoBAActionPerformed

    private void jButtonEmailBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmailBAActionPerformed
        // TODO add your handling code here:
        String email = jTextFieldIEmailBA.getText();

        if(jPanelMenuBBA.isVisible()){
            searchTable(email, "o.email", "55", jTableBibliotekarzeBA);
        }else{
            searchTable(email, "o.email", "36", jTableUzytkownicyBA);
        }
    }//GEN-LAST:event_jButtonEmailBAActionPerformed

    private void jButtonEmailBAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEmailBAMouseExited
        jTextFieldIEmailBA.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButtonEmailBAMouseExited

    private void jButtonEmailBAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEmailBAMouseEntered
        jTextFieldIEmailBA.setBackground(LibForm.newBlue);
    }//GEN-LAST:event_jButtonEmailBAMouseEntered

    private void jButtonImieBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImieBAActionPerformed
        // TODO add your handling code here:
        String imie = jTextFieldImieBA.getText();

        if(jPanelMenuBBA.isVisible()){
            searchTable(imie, "o.imie", "55", jTableBibliotekarzeBA);
        }else{
            searchTable(imie, "o.imie", "36", jTableUzytkownicyBA);
        }
    }//GEN-LAST:event_jButtonImieBAActionPerformed

    private void jButtonImieBAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonImieBAMouseExited
        // TODO add your handling code here:
        jTextFieldImieBA.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButtonImieBAMouseExited

    private void jButtonImieBAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonImieBAMouseEntered
        // TODO add your handling code here:
        jTextFieldImieBA.setBackground(LibForm.newBlue);
    }//GEN-LAST:event_jButtonImieBAMouseEntered

    private void jButtonNazwiskoBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNazwiskoBAActionPerformed
        // TODO add your handling code here:
        String nazwisko = jTextFieldINazwiskoBA.getText();

        if(jPanelMenuBBA.isVisible()){
            searchTable(nazwisko, "o.nazwisko", "55", jTableBibliotekarzeBA);
        }else{
            searchTable(nazwisko, "o.nazwisko", "36", jTableUzytkownicyBA);
        }
    }//GEN-LAST:event_jButtonNazwiskoBAActionPerformed

    private void jButtonNazwiskoBAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNazwiskoBAMouseExited
        jTextFieldINazwiskoBA.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButtonNazwiskoBAMouseExited

    private void jButtonNazwiskoBAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNazwiskoBAMouseEntered
        jTextFieldINazwiskoBA.setBackground(LibForm.newBlue);
    }//GEN-LAST:event_jButtonNazwiskoBAMouseEntered

    private void jButtonTelefonBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTelefonBAActionPerformed
        // TODO add your handling code here:
        String telefon = jTextFieldITelefonBA.getText();

        if(jPanelMenuBBA.isVisible()){
            searchTable(telefon, "o.telefon", "55", jTableBibliotekarzeBA);
        }else{
            searchTable(telefon, "o.telefon", "36", jTableUzytkownicyBA);
        }
    }//GEN-LAST:event_jButtonTelefonBAActionPerformed

    private void jButtonTelefonBAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTelefonBAMouseExited
        jTextFieldITelefonBA.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButtonTelefonBAMouseExited

    private void jButtonTelefonBAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTelefonBAMouseEntered
        jTextFieldITelefonBA.setBackground(LibForm.newBlue);
    }//GEN-LAST:event_jButtonTelefonBAMouseEntered

    private void jButtonUsunBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsunBAActionPerformed
        // TODO add your handling code here:
        String email = jTextFieldIEmailBA.getText().replaceAll("\\s+","");

        if(email.trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Wymagane pole jest puste","Uzupelnij puste pole",2);
        }
        else{

            queryToSend.add("2");                   //checkOsoba
            queryToSend.add(email);

            int checkId = Client.readWriteServer(this, queryToSend, null, null);
            if(checkId > 0){

                queryToSend.add("57");              //deleteBibliotekarz
                queryToSend.add(String.valueOf(checkId));

                if(Client.readWriteServer(this, queryToSend, null, null) == 1){
                    String logInfo = "Administrator[ " + emailUser + "] usunal bibliotekarza z emailem: [" + email + "]";
                    sendLog(logInfo, jTextAreaBA);

                    queryToSend.add("54");
                    Client.readWriteServer(this, queryToSend, jTableBibliotekarzeBA, null);
                } else {
                    System.out.println("nie ma takiego bibliotekarza");
                }
            }
        }
    }//GEN-LAST:event_jButtonUsunBAActionPerformed

    private void jButtonUsunBAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUsunBAMouseExited
        jTextFieldIEmailBA.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButtonUsunBAMouseExited

    private void jButtonUsunBAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUsunBAMouseEntered
        jTextFieldIEmailBA.setBackground(LibForm.newBlue);
    }//GEN-LAST:event_jButtonUsunBAMouseEntered

    private void jTextFieldImieBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldImieBAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldImieBAActionPerformed

    private void jTableBibliotekarzeBAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBibliotekarzeBAMouseClicked
        // TODO add your handling code here:
        int indexArr = jTableBibliotekarzeBA.getSelectedRow();
        TableModel model = jTableBibliotekarzeBA.getModel();

        jTextFieldImieBA.setText(model.getValueAt(indexArr, 1).toString().replaceAll("\\s+",""));
        jTextFieldINazwiskoBA.setText(model.getValueAt(indexArr, 2).toString().replaceAll("\\s+",""));
        jTextFieldITelefonBA.setText(model.getValueAt(indexArr, 5).toString().replaceAll("\\s+",""));
        jTextFieldIEmailBA.setText(model.getValueAt(indexArr, 6).toString().replaceAll("\\s+",""));

        jTextFieldStatBA.setText("Bibliotekarz");
    }//GEN-LAST:event_jTableBibliotekarzeBAMouseClicked

    private void jTableLogsBAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLogsBAMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableLogsBAMouseClicked

    private void jButtonOdsiezBAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOdsiezBAMouseEntered

    }//GEN-LAST:event_jButtonOdsiezBAMouseEntered

    private void jButtonOdsiezBAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOdsiezBAMouseExited

    }//GEN-LAST:event_jButtonOdsiezBAMouseExited

    private void jButtonOdsiezBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdsiezBAActionPerformed
        queryToSend.add("61");
        Client.readWriteServer(this, queryToSend, jTableLogsBA, null);
    }//GEN-LAST:event_jButtonOdsiezBAActionPerformed

    private void jButtonWyswielBA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWyswielBA1ActionPerformed
        // TODO add your handling code here:
        queryToSend.add("54");
        Client.readWriteServer(this, queryToSend, jTableBibliotekarzeBA, null);
    }//GEN-LAST:event_jButtonWyswielBA1ActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jTabbedPane1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseEntered

    private void jButtonWyswielBA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWyswielBA2ActionPerformed
        // TODO add your handling code here:
        queryToSend.add("35");
        Client.readWriteServer(this, queryToSend, jTableUzytkownicyBA, null);
    }//GEN-LAST:event_jButtonWyswielBA2ActionPerformed

    private void jTableUzytkownicyBAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUzytkownicyBAMouseClicked
        // TODO add your handling code here:
        int indexArr = jTableUzytkownicyBA.getSelectedRow();
        TableModel model = jTableUzytkownicyBA.getModel();

        jTextFieldImieBA.setText(model.getValueAt(indexArr, 1).toString().replaceAll("\\s+",""));
        jTextFieldINazwiskoBA.setText(model.getValueAt(indexArr, 2).toString().replaceAll("\\s+",""));
        jTextFieldITelefonBA.setText(model.getValueAt(indexArr, 5).toString().replaceAll("\\s+",""));
        jTextFieldIEmailBA.setText(model.getValueAt(indexArr, 6).toString().replaceAll("\\s+",""));

        jTextFieldStatBA.setText("Czytelnik");
    }//GEN-LAST:event_jTableUzytkownicyBAMouseClicked

    private void jTabbedPane1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1ComponentShown

    private void jPanelMenuBBAComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanelMenuBBAComponentShown
        // TODO add your handling code here:
        jButtonUDodajBA.setEnabled(false);
        jButtonUsunBA.setEnabled(true);
        clearAllFields();
        
        queryToSend.add("54");
        Client.readWriteServer(this, queryToSend, jTableBibliotekarzeBA, null);
    }//GEN-LAST:event_jPanelMenuBBAComponentShown

    private void jPanelMenuCBAComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanelMenuCBAComponentShown
        // TODO add your handling code here:
        jButtonUDodajBA.setEnabled(true);
        jButtonUsunBA.setEnabled(false);
        clearAllFields();
        
        queryToSend.add("35");
        Client.readWriteServer(this, queryToSend, jTableUzytkownicyBA, null);
    }//GEN-LAST:event_jPanelMenuCBAComponentShown

    private void jPanelSubmenuCz1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanelSubmenuCz1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelSubmenuCz1ComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        LibForm st = new LibForm();
        
        java.awt.EventQueue.invokeLater(() -> {
            new AdmForm(emailUser).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonEmailBA;
    private javax.swing.JButton jButtonImieBA;
    private javax.swing.JButton jButtonNazwiskoBA;
    private javax.swing.JButton jButtonOdsiezBA;
    private javax.swing.JButton jButtonTelefonBA;
    private javax.swing.JButton jButtonUDodajBA;
    private javax.swing.JButton jButtonUsunBA;
    private javax.swing.JButton jButtonWyswielBA1;
    private javax.swing.JButton jButtonWyswielBA2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelEmailBA;
    private javax.swing.JLabel jLabelEmailBA1;
    private javax.swing.JLabel jLabelImieBA;
    private javax.swing.JLabel jLabelNazwiskoBA;
    private javax.swing.JLabel jLabelTelefonBA;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelAutorzy;
    private javax.swing.JPanel jPanelConsoleK;
    private javax.swing.JPanel jPanelMenuBBA;
    private javax.swing.JPanel jPanelMenuCBA;
    private javax.swing.JPanel jPanelMenuK6;
    private javax.swing.JPanel jPanelSubmenuCz1;
    private javax.swing.JScrollPane jScrollPaneDB_Console8;
    private javax.swing.JScrollPane jScrollPaneTableB;
    private javax.swing.JScrollPane jScrollPaneTableB6;
    private javax.swing.JScrollPane jScrollPaneTableB7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPanelAdministrator;
    private javax.swing.JTable jTableBibliotekarzeBA;
    private javax.swing.JTable jTableLogsBA;
    private javax.swing.JTable jTableUzytkownicyBA;
    private javax.swing.JTextArea jTextAreaBA;
    private javax.swing.JTextField jTextFieldEmailBA;
    private javax.swing.JTextField jTextFieldIEmailBA;
    private javax.swing.JTextField jTextFieldINazwiskoBA;
    private javax.swing.JTextField jTextFieldITelefonBA;
    private javax.swing.JTextField jTextFieldImieBA;
    private javax.swing.JTextField jTextFieldStatBA;
    // End of variables declaration//GEN-END:variables
}
