package projectjavaapp;

import java.awt.Color;
import java.io.IOException;
import java.net.InetAddress;
import java.net.Socket;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static projectjavaapp.LibForm.dateForm;


public class LoginForm extends javax.swing.JFrame {
    
    static ArrayList<String> queryToSend = new ArrayList<>();
    static Socket s;
    static boolean checkConn = false;
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginForm().setVisible(true);
        });
        
    }


    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
            }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    static public void connectToServer(){
        if(!checkConn){
            try
            {
                InetAddress ip = InetAddress.getByName("localhost");        //tworzenie nowego polaczenia

                s = new Socket(ip, 5056);
                checkConn = true;
            }catch(IOException e){
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, e);
            }  
        }
    }
    
    private void sendLog(String useremail){    
        
        String logInfo = "Uzytkownik z emailem: [" +useremail+ "] zostal zalogowany";
        LocalDateTime date = LocalDateTime.now();
        queryToSend.add("60");
        queryToSend.add(date.format(dateForm));
        queryToSend.add(logInfo);
        Client.readWriteServer(this, queryToSend, null, null);
        
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_login = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jProgressBar = new javax.swing.JProgressBar();
        jPasswordFieldLogin_password = new javax.swing.JPasswordField();
        jTextFieldLogin_username = new javax.swing.JTextField();
        jPanel_register = new javax.swing.JPanel();
        jTextFieldRegister_surname = new javax.swing.JTextField();
        jTextFieldRegister_name = new javax.swing.JTextField();
        jPasswordFieldRegister_password = new javax.swing.JPasswordField();
        jPasswordFieldRegister_passwordConfirm = new javax.swing.JPasswordField();
        jTextFieldRegister_email = new javax.swing.JTextField();
        jTextFieldRegister_phone = new javax.swing.JTextField();
        jButtonRegister = new javax.swing.JButton();
        jLabelName = new javax.swing.JLabel();
        jLabelSurname = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelPhone = new javax.swing.JLabel();
        jLabelPass = new javax.swing.JLabel();
        jLabelPassConf = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldRegister_date = new javax.swing.JTextField();
        jRadioButtonRegister_female = new javax.swing.JRadioButton();
        jRadioButtonRegister_male = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitle.setText("Logowanie");

        jButtonLogin.setText("Logowanie");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginjButtonLoginActionPerformed(evt);
            }
        });

        jProgressBar.setBackground(new java.awt.Color(242, 242, 242));

        jPasswordFieldLogin_password.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordFieldLogin_password.setText("haslo");
        jPasswordFieldLogin_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldLogin_passwordjPasswordFieldPassword_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldLogin_passwordjPasswordFieldPassword_passwordFocusLost(evt);
            }
        });
        jPasswordFieldLogin_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldLogin_passwordjPasswordFieldPassword_passwordActionPerformed(evt);
            }
        });

        jTextFieldLogin_username.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldLogin_username.setText("email uzytkownika");
        jTextFieldLogin_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldLogin_usernamejTextFieldLogin_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldLogin_usernamejTextFieldLogin_usernameFocusLost(evt);
            }
        });
        jTextFieldLogin_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLogin_usernameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_loginLayout = new javax.swing.GroupLayout(jPanel_login);
        jPanel_login.setLayout(jPanel_loginLayout);
        jPanel_loginLayout.setHorizontalGroup(
            jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_loginLayout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordFieldLogin_password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLogin_username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_loginLayout.createSequentialGroup()
                        .addComponent(jLabelTitle)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_loginLayout.createSequentialGroup()
                        .addComponent(jButtonLogin)
                        .addGap(34, 34, 34)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jPanel_loginLayout.setVerticalGroup(
            jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_loginLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jLabelTitle)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldLogin_username, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldLogin_password, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonLogin)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Logowanie", jPanel_login);

        jTextFieldRegister_surname.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldRegister_surname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldRegister_surnamejTextFieldLogin_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldRegister_surnamejTextFieldLogin_usernameFocusLost(evt);
            }
        });
        jTextFieldRegister_surname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRegister_surnameActionPerformed(evt);
            }
        });

        jTextFieldRegister_name.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldRegister_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldRegister_namejTextFieldLogin_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldRegister_namejTextFieldLogin_usernameFocusLost(evt);
            }
        });
        jTextFieldRegister_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRegister_nameActionPerformed(evt);
            }
        });

        jPasswordFieldRegister_password.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordFieldRegister_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldRegister_passwordjPasswordFieldPassword_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldRegister_passwordjPasswordFieldPassword_passwordFocusLost(evt);
            }
        });
        jPasswordFieldRegister_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldRegister_passwordjPasswordFieldPassword_passwordActionPerformed(evt);
            }
        });

        jPasswordFieldRegister_passwordConfirm.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordFieldRegister_passwordConfirm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldRegister_passwordConfirmjPasswordFieldPassword_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldRegister_passwordConfirmjPasswordFieldPassword_passwordFocusLost(evt);
            }
        });
        jPasswordFieldRegister_passwordConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldRegister_passwordConfirmjPasswordFieldPassword_passwordActionPerformed(evt);
            }
        });

        jTextFieldRegister_email.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldRegister_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldRegister_emailjTextFieldLogin_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldRegister_emailjTextFieldLogin_usernameFocusLost(evt);
            }
        });
        jTextFieldRegister_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRegister_emailActionPerformed(evt);
            }
        });

        jTextFieldRegister_phone.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldRegister_phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldRegister_phonejTextFieldLogin_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldRegister_phonejTextFieldLogin_usernameFocusLost(evt);
            }
        });
        jTextFieldRegister_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRegister_phoneActionPerformed(evt);
            }
        });
        jTextFieldRegister_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldRegister_phoneKeyTyped(evt);
            }
        });

        jButtonRegister.setText("Rejestracja");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });

        jLabelName.setText("Imię:");

        jLabelSurname.setText("Nazwisko:");

        jLabelEmail.setText("Email:");

        jLabelPhone.setText("Telefon:");

        jLabelPass.setText("Hasło:");

        jLabelPassConf.setText("Postwierdź hasło:");

        jLabel1.setText("Data urodzenia:");

        jLabel2.setText("Płeć:");

        jTextFieldRegister_date.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldRegister_date.setText("dd/mm/rrrr");
        jTextFieldRegister_date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldRegister_datejTextFieldLogin_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldRegister_datejTextFieldLogin_usernameFocusLost(evt);
            }
        });
        jTextFieldRegister_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRegister_dateActionPerformed(evt);
            }
        });

        buttonGroup.add(jRadioButtonRegister_female);
        jRadioButtonRegister_female.setSelected(true);
        jRadioButtonRegister_female.setText("Kobieta");
        jRadioButtonRegister_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRegister_femaleActionPerformed(evt);
            }
        });

        buttonGroup.add(jRadioButtonRegister_male);
        jRadioButtonRegister_male.setText("Mężczyzna");

        javax.swing.GroupLayout jPanel_registerLayout = new javax.swing.GroupLayout(jPanel_register);
        jPanel_register.setLayout(jPanel_registerLayout);
        jPanel_registerLayout.setHorizontalGroup(
            jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_registerLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldRegister_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel_registerLayout.createSequentialGroup()
                            .addGroup(jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelSurname)
                                .addComponent(jLabelPass)
                                .addComponent(jLabelPassConf)
                                .addComponent(jLabelPhone)
                                .addComponent(jLabelEmail)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel_registerLayout.createSequentialGroup()
                                    .addComponent(jRadioButtonRegister_female)
                                    .addGap(23, 23, 23)
                                    .addComponent(jRadioButtonRegister_male))
                                .addComponent(jTextFieldRegister_date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldRegister_email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldRegister_phone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPasswordFieldRegister_password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPasswordFieldRegister_passwordConfirm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_registerLayout.createSequentialGroup()
                            .addGap(79, 79, 79)
                            .addComponent(jLabelName)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldRegister_name, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_registerLayout.createSequentialGroup()
                        .addComponent(jButtonRegister)
                        .addGap(48, 48, 48)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel_registerLayout.setVerticalGroup(
            jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_registerLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRegister_name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRegister_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSurname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldRegister_date, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButtonRegister_female)
                    .addComponent(jRadioButtonRegister_male))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRegister_email, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRegister_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldRegister_password, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldRegister_passwordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPassConf))
                .addGap(18, 18, 18)
                .addComponent(jButtonRegister)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Rejestracja", jPanel_register);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldLogin_usernamejTextFieldLogin_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldLogin_usernamejTextFieldLogin_usernameFocusLost
        // TODO add your handling code here:
        String usernameValue = jTextFieldLogin_username.getText().trim().toLowerCase();

        if(usernameValue.equals("email uzytkownika") || usernameValue.equals(""))
        {
            jTextFieldLogin_username.setText("email uzytkownika");
            jTextFieldLogin_username.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jTextFieldLogin_usernamejTextFieldLogin_usernameFocusLost

    private void jTextFieldLogin_usernamejTextFieldLogin_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldLogin_usernamejTextFieldLogin_usernameFocusGained
        // TODO add your handling code here:
        String usernameValue = jTextFieldLogin_username.getText().trim().toLowerCase();

        if(usernameValue.equals("email uzytkownika"))
        {
            jTextFieldLogin_username.setText("");
            jTextFieldLogin_username.setForeground(Color.black);
        }
        
    }//GEN-LAST:event_jTextFieldLogin_usernamejTextFieldLogin_usernameFocusGained

    private void jPasswordFieldLogin_passwordjPasswordFieldPassword_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldLogin_passwordjPasswordFieldPassword_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldLogin_passwordjPasswordFieldPassword_passwordActionPerformed

    private void jPasswordFieldLogin_passwordjPasswordFieldPassword_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldLogin_passwordjPasswordFieldPassword_passwordFocusLost
        // TODO add your handling code here:
        String passValue = String.valueOf(jPasswordFieldLogin_password.getPassword()).trim().toLowerCase();

        if(passValue.equals("haslo") || passValue.equals(""))
        {
            jPasswordFieldLogin_password.setText("haslo");
            jPasswordFieldLogin_password.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jPasswordFieldLogin_passwordjPasswordFieldPassword_passwordFocusLost

    private void jPasswordFieldLogin_passwordjPasswordFieldPassword_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldLogin_passwordjPasswordFieldPassword_passwordFocusGained
        // TODO add your handling code here:
        String passValue = String.valueOf(jPasswordFieldLogin_password.getPassword()).trim().toLowerCase();

        if(passValue.equals("haslo"))
        {
            jPasswordFieldLogin_password.setText("");
            jPasswordFieldLogin_password.setForeground(Color.black);
        }
    }//GEN-LAST:event_jPasswordFieldLogin_passwordjPasswordFieldPassword_passwordFocusGained

    private void jButtonLoginjButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginjButtonLoginActionPerformed
        // TODO add your handling code here:
         connectToServer();
         
         String useremail = jTextFieldLogin_username.getText();
         String password = String.valueOf(jPasswordFieldLogin_password.getPassword());
         
         if(jTextFieldLogin_username.getText().trim().equals("email uzytkownika")){
             JOptionPane.showMessageDialog(null, "Wpisz email","Pusty email",2);
         }
         else if(password.trim().equals("haslo")){
             JOptionPane.showMessageDialog(null, "Wpisz haslo","Puste haslo",2);
         }
        else{            
             queryToSend.add("1");
             queryToSend.add(useremail);
             queryToSend.add(password);
             
             int logCh = Client.readWriteServer(this, queryToSend, null, null);
             
  
             
             switch (logCh) {
                 case 1:
                     {
                         sendLog(useremail);
                         AdmForm form = new AdmForm(useremail);
                         form.setVisible(true);
                         form.setLocationRelativeTo(null);
                         this.dispose();
                         checkConn = false;
                         break;
                     }
                 case 2:
                     {
                         sendLog(useremail);
                         LibForm form = new LibForm(useremail);
                         form.setVisible(true);
                         form.setLocationRelativeTo(null);
                         this.dispose();
                         checkConn = false;
                         break;
                     }
                 case 3:
                     {
                         sendLog(useremail);
                         UsrForm form = new UsrForm(useremail);
                         form.setVisible(true);
                         form.setLocationRelativeTo(null);
                         this.dispose();
                         checkConn = false;
                         break;
                     }
                 default:
                     JOptionPane.showMessageDialog(null, "Bledny email lub haslo","Blad logowania",2);
                     break;
             }
         }
    }//GEN-LAST:event_jButtonLoginjButtonLoginActionPerformed

    private void jTextFieldLogin_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLogin_usernameActionPerformed
        
    }//GEN-LAST:event_jTextFieldLogin_usernameActionPerformed

    private void jTextFieldRegister_surnamejTextFieldLogin_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldRegister_surnamejTextFieldLogin_usernameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegister_surnamejTextFieldLogin_usernameFocusGained

    private void jTextFieldRegister_surnamejTextFieldLogin_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldRegister_surnamejTextFieldLogin_usernameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegister_surnamejTextFieldLogin_usernameFocusLost

    private void jTextFieldRegister_surnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRegister_surnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegister_surnameActionPerformed

    private void jTextFieldRegister_namejTextFieldLogin_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldRegister_namejTextFieldLogin_usernameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegister_namejTextFieldLogin_usernameFocusGained

    private void jTextFieldRegister_namejTextFieldLogin_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldRegister_namejTextFieldLogin_usernameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegister_namejTextFieldLogin_usernameFocusLost

    private void jTextFieldRegister_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRegister_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegister_nameActionPerformed

    private void jPasswordFieldRegister_passwordjPasswordFieldPassword_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldRegister_passwordjPasswordFieldPassword_passwordFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldRegister_passwordjPasswordFieldPassword_passwordFocusGained

    private void jPasswordFieldRegister_passwordjPasswordFieldPassword_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldRegister_passwordjPasswordFieldPassword_passwordFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldRegister_passwordjPasswordFieldPassword_passwordFocusLost

    private void jPasswordFieldRegister_passwordjPasswordFieldPassword_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldRegister_passwordjPasswordFieldPassword_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldRegister_passwordjPasswordFieldPassword_passwordActionPerformed

    private void jPasswordFieldRegister_passwordConfirmjPasswordFieldPassword_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldRegister_passwordConfirmjPasswordFieldPassword_passwordFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldRegister_passwordConfirmjPasswordFieldPassword_passwordFocusGained

    private void jPasswordFieldRegister_passwordConfirmjPasswordFieldPassword_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldRegister_passwordConfirmjPasswordFieldPassword_passwordFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldRegister_passwordConfirmjPasswordFieldPassword_passwordFocusLost

    private void jPasswordFieldRegister_passwordConfirmjPasswordFieldPassword_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldRegister_passwordConfirmjPasswordFieldPassword_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldRegister_passwordConfirmjPasswordFieldPassword_passwordActionPerformed

    private void jTextFieldRegister_emailjTextFieldLogin_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldRegister_emailjTextFieldLogin_usernameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegister_emailjTextFieldLogin_usernameFocusGained

    private void jTextFieldRegister_emailjTextFieldLogin_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldRegister_emailjTextFieldLogin_usernameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegister_emailjTextFieldLogin_usernameFocusLost

    private void jTextFieldRegister_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRegister_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegister_emailActionPerformed

    private void jTextFieldRegister_phonejTextFieldLogin_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldRegister_phonejTextFieldLogin_usernameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegister_phonejTextFieldLogin_usernameFocusGained

    private void jTextFieldRegister_phonejTextFieldLogin_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldRegister_phonejTextFieldLogin_usernameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegister_phonejTextFieldLogin_usernameFocusLost

    private void jTextFieldRegister_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRegister_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegister_phoneActionPerformed

    private void jTextFieldRegister_datejTextFieldLogin_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldRegister_datejTextFieldLogin_usernameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegister_datejTextFieldLogin_usernameFocusGained

    private void jTextFieldRegister_datejTextFieldLogin_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldRegister_datejTextFieldLogin_usernameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegister_datejTextFieldLogin_usernameFocusLost

    private void jTextFieldRegister_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRegister_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegister_dateActionPerformed

    private void jRadioButtonRegister_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRegister_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonRegister_femaleActionPerformed

    private void jTextFieldRegister_phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRegister_phoneKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldRegister_phoneKeyTyped

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        // TODO add your handling code here:
        connectToServer();
        
        String rname = jTextFieldRegister_name.getText();
        String rsname = jTextFieldRegister_surname.getText();
        String rdate = jTextFieldRegister_date.getText();
        String remail = jTextFieldRegister_email.getText();
        String rphone = jTextFieldRegister_phone.getText();
        String rpass1 = String.valueOf(jPasswordFieldRegister_password.getPassword());
        String gender = "kobieta";
        
        if(jRadioButtonRegister_male.isSelected()) {
            gender = "mężczyzna";
        }
        
        if(verifyFields()) {
            queryToSend.add("2");
            queryToSend.add(remail);
            if(Client.readWriteServer(this, queryToSend, null, null) <= 0) {
                if(rphone.length() > 12){
                    JOptionPane.showMessageDialog(null, "Podany numer telefonu jest za dlugi","Podaj poprawny numer telefonu",2);
                }else{
                
                
                    queryToSend.add("10");
                    queryToSend.add(rname);
                    queryToSend.add(rsname);
                    queryToSend.add(rdate);
                    queryToSend.add(gender);
                    queryToSend.add(rphone);
                    queryToSend.add(remail);
                    queryToSend.add(rpass1);
                    
                    if(Client.readWriteServer(this, queryToSend, null, null) == 1){
                        JOptionPane.showMessageDialog(null, "Twoje konto zostalo utworzone. Mozesz sie teraz zalogowac.");
                        
                        String logInfo = "Utworzono nowe konto na emial: [" +remail+ "]";
                        LocalDateTime date = LocalDateTime.now();
                        queryToSend.add("60");
                        queryToSend.add(date.format(dateForm));
                        queryToSend.add(logInfo);
                        Client.readWriteServer(this, queryToSend, null, null);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Osoba z takim adresem email juz istnieje","Blad",2); 
            }
        }
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    
    //puste pola
    public boolean verifyFields()
    {
        String rname = jTextFieldRegister_name.getText();
        String rsname = jTextFieldRegister_surname.getText();
        String rdate = jTextFieldRegister_date.getText();
        String remail = jTextFieldRegister_email.getText();
        String rphone = jTextFieldRegister_phone.getText();
        String rpass1 = String.valueOf(jPasswordFieldRegister_password.getPassword());
        String rpass2 = String.valueOf(jPasswordFieldRegister_passwordConfirm.getPassword());
        
        if(rname.trim().equals("") || rsname.trim().equals("") 
                || rdate.trim().equals("") || remail.trim().equals("")
                || rphone.trim().equals("") || rpass1.trim().equals("")
                || rpass2.trim().equals("")) 
        {
           
            JOptionPane.showMessageDialog(null, "Jedno lub więcej pól jest puste","Uzupelnij puste pola",2);
            return false;
        }
        //sprawdzanie hasel
        else if(!rpass1.equals(rpass2)) {
            JOptionPane.showMessageDialog(null, "Hasla nie sa takie same","Sprawdz hasla",2);
            return false;
        }//jesli ok
        else{
        return true;
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JLabel jLabelPassConf;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelSurname;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel_login;
    private javax.swing.JPanel jPanel_register;
    private javax.swing.JPasswordField jPasswordFieldLogin_password;
    private javax.swing.JPasswordField jPasswordFieldRegister_password;
    private javax.swing.JPasswordField jPasswordFieldRegister_passwordConfirm;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JRadioButton jRadioButtonRegister_female;
    private javax.swing.JRadioButton jRadioButtonRegister_male;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldLogin_username;
    private javax.swing.JTextField jTextFieldRegister_date;
    private javax.swing.JTextField jTextFieldRegister_email;
    private javax.swing.JTextField jTextFieldRegister_name;
    private javax.swing.JTextField jTextFieldRegister_phone;
    private javax.swing.JTextField jTextFieldRegister_surname;
    // End of variables declaration//GEN-END:variables
}
