INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Nauki ekonomiczne', NULL);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Nauki humanistyczne', NULL);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Nauki matematyczno-przyrodnicze', NULL);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Nauki społeczne', NULL);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Informatyka', NULL);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Literatura piękna', NULL);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Medycyna', NULL);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Prawo', NULL);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Albumy, atlasy', NULL);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Literatura dla dzieci i młodzieży', NULL);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Literatura popularnonaukowa', NULL);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Poradniki', NULL);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Przewodniki', NULL);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Sport', NULL);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Inne', NULL);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Finanse i bankowość', 1);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Usługi', 1);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Publikacje Obcojęzyczne', 1);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Filologia polska', 2);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Historia', 2);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Publikacje Obcojęzyczne', 2);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Biologia', 3);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Chemia', 3);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Fizyka', 3);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Matematyka', 3);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Publikacje Obcojęzyczne', 3);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Filozofia', 4);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Pedagogika', 4);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Publikacje Obcojęzyczne', 4);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Publikacje Obcojęzyczne', 4);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Algorytmika', 5);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Bazy danych', 5);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Publikacje Obcojęzyczne', 5);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Fantastyka', 6);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Kryminał, sensacja, thriller', 6);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Publikacje Obcojęzyczne', 6);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Chirurgia', 7);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Farmakologia', 7);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Anatomia', 7);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Publikacje Obcojęzyczne', 7);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Prawo karne', 8);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Prawo cywilne', 8);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Publikacje Obcojęzyczne', 8);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Literatura dla dzieci i młodzieży', 15);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Różne', 15);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Publikacje Obcojęzyczne', 15);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Gramatyka języka polskiego', 19);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Historia literatury', 19);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Literatura polska', 19);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Archeologia', 20);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Historia Europy', 20);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Historia Polski', 20);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Starożytność', 20);
INSERT INTO KATEGORIA(nazwa_kategorii, rodzic_id) VALUES ('Średniowiecze', 20);

INSERT INTO WYDAWNICTWO(nazwa_wydawnictwa, miasto) VALUES ('Wiedza i Praktyka', 'Warszawa');
INSERT INTO WYDAWNICTWO(nazwa_wydawnictwa, miasto) VALUES ('Wydawnictwo Uniwersytetu Ekonomicznego w Krakowie', 'Kraków');
INSERT INTO WYDAWNICTWO(nazwa_wydawnictwa, miasto) VALUES ('Uniwersytet Ekonomiczny w Poznaniu', 'Poznań');
INSERT INTO WYDAWNICTWO(nazwa_wydawnictwa, miasto) VALUES ('Wydawnictwo Naukowe PWN', 'Warszawa');
INSERT INTO WYDAWNICTWO(nazwa_wydawnictwa, miasto) VALUES ('Uniwersytet Jana Kochanowskiego', 'Kielce');
INSERT INTO WYDAWNICTWO(nazwa_wydawnictwa, miasto) VALUES ('Literatura', 'Łódź');
INSERT INTO WYDAWNICTWO(nazwa_wydawnictwa, miasto) VALUES ('Biblioteka Akustyczna', 'Warszawa');
INSERT INTO WYDAWNICTWO(nazwa_wydawnictwa, miasto) VALUES ('Wydawnictwo BOSZ', 'Lesko');
INSERT INTO WYDAWNICTWO(nazwa_wydawnictwa, miasto) VALUES ('Agora', 'Warszawa');
INSERT INTO WYDAWNICTWO(nazwa_wydawnictwa, miasto) VALUES ('Smak Słowa', 'Sopot');
INSERT INTO WYDAWNICTWO(nazwa_wydawnictwa, miasto) VALUES ('Wydawnictwo Akademickie Dialog', 'Warszawa');
INSERT INTO WYDAWNICTWO(nazwa_wydawnictwa, miasto) VALUES ('Armoryka', 'Sandomierz');
INSERT INTO WYDAWNICTWO(nazwa_wydawnictwa, miasto) VALUES ('Imprint sp. z o.o.', 'Warszawa');
INSERT INTO WYDAWNICTWO(nazwa_wydawnictwa, miasto) VALUES ('Wydawnictwo Uniwersytetu Łódzkiego', 'Łódź');
INSERT INTO WYDAWNICTWO(nazwa_wydawnictwa, miasto) VALUES ('Wydawnictwo Naukowe Uniwersytetu Mikołaja Kopernika', 'Toruń');
INSERT INTO WYDAWNICTWO(nazwa_wydawnictwa, miasto) VALUES ('Wydawnictwa AGH', 'Kraków');
INSERT INTO WYDAWNICTWO(nazwa_wydawnictwa, miasto) VALUES ('Oficyna Wydawnicza Politechniki Warszawskiej', 'Warszawa');
INSERT INTO WYDAWNICTWO(nazwa_wydawnictwa, miasto) VALUES ('Akademia Marynarki Wojennej', 'Gdynia');
INSERT INTO WYDAWNICTWO(nazwa_wydawnictwa, miasto) VALUES ('Wydawnictwo Naukowe Uniwersytetu im. Adama Mickiewicza', 'Poznań');
INSERT INTO WYDAWNICTWO(nazwa_wydawnictwa, miasto) VALUES ('Universitas', 'Kraków');

INSERT INTO KSIAZKA(tytul, kategoria_id, wydawnictwo_id, rok_wydania, liczba_sztuk) VALUES ('Sprawozdawczość budżetowa 2022', 16, 1, 2022, 10);
INSERT INTO KSIAZKA(tytul, kategoria_id, wydawnictwo_id, rok_wydania, liczba_sztuk) VALUES ('Modele świadczenia usług w handlu międzynarodowym', 17, 2, 2021, 4);
INSERT INTO KSIAZKA(tytul, kategoria_id, wydawnictwo_id, rok_wydania, liczba_sztuk) VALUES ('Vademecum usług bankowych', 17, 3, 2021, 12);
INSERT INTO KSIAZKA(tytul, kategoria_id, wydawnictwo_id, rok_wydania, liczba_sztuk) VALUES ('Podstawy ubezpieczeń majątkowych', 16, 4, 2022, 10);
INSERT INTO KSIAZKA(tytul, kategoria_id, wydawnictwo_id, rok_wydania, liczba_sztuk) VALUES ('Marketing mix of food industry enterprises', 18, 5, 2020, 2);
INSERT INTO KSIAZKA(tytul, kategoria_id, wydawnictwo_id, rok_wydania, liczba_sztuk) VALUES ('Uciekinierzy', 44, 6, 2017, 5);
INSERT INTO KSIAZKA(tytul, kategoria_id, wydawnictwo_id, rok_wydania, liczba_sztuk) VALUES ('Kocie historie', 44, 7, 2008, 9);
INSERT INTO KSIAZKA(tytul, kategoria_id, wydawnictwo_id, rok_wydania, liczba_sztuk) VALUES ('Strach się bać', 19, 8, 2022, 11);
INSERT INTO KSIAZKA(tytul, kategoria_id, wydawnictwo_id, rok_wydania, liczba_sztuk) VALUES ('Mówi się. Porady językowe profesora Bralczyka', 19, 4, 2020, 6);
INSERT INTO KSIAZKA(tytul, kategoria_id, wydawnictwo_id, rok_wydania, liczba_sztuk) VALUES ('Na drugie Stanisław. Nowa księga imion', 11, 9, 2015, 3);
INSERT INTO KSIAZKA(tytul, kategoria_id, wydawnictwo_id, rok_wydania, liczba_sztuk) VALUES ('Biała mapa', 19, 10, 2022, 14);
INSERT INTO KSIAZKA(tytul, kategoria_id, wydawnictwo_id, rok_wydania, liczba_sztuk) VALUES ('Chiński feniks', 20, 11, 2022, 18);
INSERT INTO KSIAZKA(tytul, kategoria_id, wydawnictwo_id, rok_wydania, liczba_sztuk) VALUES ('Dzieje wypraw krzyżowych', 20, 12, 2022, 11);
INSERT INTO KSIAZKA(tytul, kategoria_id, wydawnictwo_id, rok_wydania, liczba_sztuk) VALUES ('Cezarom oddaj', 6, 13, 2012, 4);
INSERT INTO KSIAZKA(tytul, kategoria_id, wydawnictwo_id, rok_wydania, liczba_sztuk) VALUES ('Polska. Eseje o stuleciu', 20, 8, 2022, 19);
INSERT INTO KSIAZKA(tytul, kategoria_id, wydawnictwo_id, rok_wydania, liczba_sztuk) VALUES ('Entre la tradición y la novedad', 20, 14, 2020, 4);
INSERT INTO KSIAZKA(tytul, kategoria_id, wydawnictwo_id, rok_wydania, liczba_sztuk) VALUES ('Krótki kurs. Zachowanie zwierząt', 22, 4, 2022, 21);
INSERT INTO KSIAZKA(tytul, kategoria_id, wydawnictwo_id, rok_wydania, liczba_sztuk) VALUES ('Metody analityczne w ocenie jakości wody', 22, 15, 2021, 5);
INSERT INTO KSIAZKA(tytul, kategoria_id, wydawnictwo_id, rok_wydania, liczba_sztuk) VALUES ('Chemia leków i proleków', 23, 4, 2022, 13);
INSERT INTO KSIAZKA(tytul, kategoria_id, wydawnictwo_id, rok_wydania, liczba_sztuk) VALUES ('Badania nanomateriałów z wykorzystaniem mikroskopii elektronowej', 23, 15, 2022, 7);
INSERT INTO KSIAZKA(tytul, kategoria_id, wydawnictwo_id, rok_wydania, liczba_sztuk) VALUES ('Wybrane Rozdziały Matematycznych Metod Fizyki', 24, 16, 2021, 3);
INSERT INTO KSIAZKA(tytul, kategoria_id, wydawnictwo_id, rok_wydania, liczba_sztuk) VALUES ('Fizyka kwantowa w pigułce', 24, 4, 2022, 9);
INSERT INTO KSIAZKA(tytul, kategoria_id, wydawnictwo_id, rok_wydania, liczba_sztuk) VALUES ('Teoria liczb z programem Mathematica', 25, 4, 2022, 12);
INSERT INTO KSIAZKA(tytul, kategoria_id, wydawnictwo_id, rok_wydania, liczba_sztuk) VALUES ('Matematyka. 30 wykładów z ćwiczeniami', 25, 17, 2022, 21);
INSERT INTO KSIAZKA(tytul, kategoria_id, wydawnictwo_id, rok_wydania, liczba_sztuk) VALUES ('Voyage planning', 26, 18, 2020, 2);
INSERT INTO KSIAZKA(tytul, kategoria_id, wydawnictwo_id, rok_wydania, liczba_sztuk) VALUES ('Tradycja i tradycjonalizm w dyskursie kulturowym', 27, 19, 2021, 5);
INSERT INTO KSIAZKA(tytul, kategoria_id, wydawnictwo_id, rok_wydania, liczba_sztuk) VALUES ('Wiedza jako opowieść', 27, 20, 2022, 2);

INSERT INTO AUTOR(imie, nazwisko, miasto, kraj, data_urodzenia, data_smierci) VALUES ('Barbara', 'Jarosz', 'Warszawa', 'Polska', to_date('16.02.1977', 'DD.MM.YYYY'), NULL);
INSERT INTO AUTOR(imie, nazwisko, miasto, kraj, data_urodzenia, data_smierci) VALUES ('Elżbieta', 'Bombińska', 'Kraków', 'Polska', to_date('01.08.1973', 'DD.MM.YYYY'), NULL);
INSERT INTO AUTOR(imie, nazwisko, miasto, kraj, data_urodzenia, data_smierci) VALUES ('Anna', 'Iwańczuk-Kaliska', 'Poznań', 'Polska', to_date('11.02.1983', 'DD.MM.YYYY'), NULL);
INSERT INTO AUTOR(imie, nazwisko, miasto, kraj, data_urodzenia, data_smierci) VALUES ('Paweł', 'Marszałek', 'Poznań', 'Polska', to_date('03.06.1986', 'DD.MM.YYYY'), NULL);
INSERT INTO AUTOR(imie, nazwisko, miasto, kraj, data_urodzenia, data_smierci) VALUES ('Lesław', 'Gajek', 'Łódź', 'Polska', to_date('23.04.1956', 'DD.MM.YYYY'), NULL);
INSERT INTO AUTOR(imie, nazwisko, miasto, kraj, data_urodzenia, data_smierci) VALUES ('Tomasz', 'Trojanowski', 'Warszawa', 'Polska', to_date('03/11/1965', 'DD.MM.YYYY'), NULL);
INSERT INTO AUTOR(imie, nazwisko, miasto, kraj, data_urodzenia, data_smierci) VALUES ('Jerzy', 'Bralczyk', 'Ciechanów', 'Polska', to_date('17.08.1947', 'DD.MM.YYYY'), NULL);
INSERT INTO AUTOR(imie, nazwisko, miasto, kraj, data_urodzenia, data_smierci) VALUES ('Michał', 'Ogórek', 'Katowice', 'Polska', to_date('17.08.1955', 'DD.MM.YYYY'), NULL);
INSERT INTO AUTOR(imie, nazwisko, miasto, kraj, data_urodzenia, data_smierci) VALUES ('Cecilie', 'Enger', 'Oslo', 'Norwegia', to_date('22.01.1963', 'DD.MM.YYYY'), NULL);
INSERT INTO AUTOR(imie, nazwisko, miasto, kraj, data_urodzenia, data_smierci) VALUES ('Bogdan', 'Góralczyk', 'Siedlce', 'Polska', to_date('01.09.1954', 'DD.MM.YYYY'), NULL);
INSERT INTO AUTOR(imie, nazwisko, miasto, kraj, data_urodzenia, data_smierci) VALUES ('Antoni', 'Lange', 'Warszawa', 'Polska', to_date('19.03.1862', 'DD.MM.YYYY'), to_date('11.08.1929', 'DD.MM.YYYY'));
INSERT INTO AUTOR(imie, nazwisko, miasto, kraj, data_urodzenia, data_smierci) VALUES ('Michał', 'Kleiber', 'Warszawa', 'Polska', to_date('29.01.1946', 'DD.MM.YYYY'), NULL);
INSERT INTO AUTOR(imie, nazwisko, miasto, kraj, data_urodzenia, data_smierci) VALUES ('Aman', 'Rosales Rodriguez', 'Almería', 'Hiszpania', to_date('09.05.1958', 'DD.MM.YYYY'), NULL);
INSERT INTO AUTOR(imie, nazwisko, miasto, kraj, data_urodzenia, data_smierci) VALUES ('Tristram', 'Wyatt', 'Londyn', 'Wielka Brytania', to_date('15.04.1956', 'DD.MM.YYYY'), NULL);
INSERT INTO AUTOR(imie, nazwisko, miasto, kraj, data_urodzenia, data_smierci) VALUES ('Anna', 'Gacek', 'Bytom', 'Polska', to_date('22.08.1981', 'DD.MM.YYYY'), NULL);
INSERT INTO AUTOR(imie, nazwisko, miasto, kraj, data_urodzenia, data_smierci) VALUES ('Ilona', 'Wandzik', 'Katowice', 'Polska', to_date('05.01.1974', 'DD.MM.YYYY'), NULL);
INSERT INTO AUTOR(imie, nazwisko, miasto, kraj, data_urodzenia, data_smierci) VALUES ('Grzegorz', 'Trykowski', 'Toruń', 'Polska', to_date('02.07.1981', 'DD.MM.YYYY'), NULL);
INSERT INTO AUTOR(imie, nazwisko, miasto, kraj, data_urodzenia, data_smierci) VALUES ('Andrzej', 'Lenda', 'Kraków', 'Polska', to_date('07.11.1943', 'DD.MM.YYYY'), to_date('26.04.2017', 'DD.MM.YYYY'));
INSERT INTO AUTOR(imie, nazwisko, miasto, kraj, data_urodzenia, data_smierci) VALUES ('Sten', 'Odenwald', 'Karlskoga', 'Szwecja', to_date('14.02.1952', 'DD.MM.YYYY'), NULL);
INSERT INTO AUTOR(imie, nazwisko, miasto, kraj, data_urodzenia, data_smierci) VALUES ('Piotr', 'Zarzycki', 'Warszawa', 'Polska', to_date('23.08.1956', 'DD.MM.YYYY'), NULL);
INSERT INTO AUTOR(imie, nazwisko, miasto, kraj, data_urodzenia, data_smierci) VALUES ('Jan', 'Nawrocki', 'Warszawa', 'Polska', to_date('05.12.1964', 'DD.MM.YYYY'), NULL);
INSERT INTO AUTOR(imie, nazwisko, miasto, kraj, data_urodzenia, data_smierci) VALUES ('Czesław', 'Dyrcz', 'Przemyśl', 'Polska', to_date('05.12.1955', 'DD.MM.YYYY'), NULL);
INSERT INTO AUTOR(imie, nazwisko, miasto, kraj, data_urodzenia, data_smierci) VALUES ('Marek', 'Jedliński', 'Poznań', 'Polska', to_date('09.04.1981', 'DD.MM.YYYY'), NULL);
INSERT INTO AUTOR(imie, nazwisko, miasto, kraj, data_urodzenia, data_smierci) VALUES ('Rafał', 'Maciąg', 'Kraków', 'Polska', to_date('01.08.1955', 'DD.MM.YYYY'), NULL);

INSERT INTO AUTOR_KSIAZKA(autor_id, ksiazka_id) VALUES (1, 1);
INSERT INTO AUTOR_KSIAZKA(autor_id, ksiazka_id) VALUES (2, 2);
INSERT INTO AUTOR_KSIAZKA(autor_id, ksiazka_id) VALUES (3, 3);
INSERT INTO AUTOR_KSIAZKA(autor_id, ksiazka_id) VALUES (4, 3);
INSERT INTO AUTOR_KSIAZKA(autor_id, ksiazka_id) VALUES (5, 4);
INSERT INTO AUTOR_KSIAZKA(autor_id, ksiazka_id) VALUES (6, 5);
INSERT INTO AUTOR_KSIAZKA(autor_id, ksiazka_id) VALUES (6, 6);
INSERT INTO AUTOR_KSIAZKA(autor_id, ksiazka_id) VALUES (6, 7);
INSERT INTO AUTOR_KSIAZKA(autor_id, ksiazka_id) VALUES (7, 8);
INSERT INTO AUTOR_KSIAZKA(autor_id, ksiazka_id) VALUES (7, 9);
INSERT INTO AUTOR_KSIAZKA(autor_id, ksiazka_id) VALUES (7, 10);
INSERT INTO AUTOR_KSIAZKA(autor_id, ksiazka_id) VALUES (8, 10);
INSERT INTO AUTOR_KSIAZKA(autor_id, ksiazka_id) VALUES (9, 11);
INSERT INTO AUTOR_KSIAZKA(autor_id, ksiazka_id) VALUES (10, 12);
INSERT INTO AUTOR_KSIAZKA(autor_id, ksiazka_id) VALUES (11, 13);
INSERT INTO AUTOR_KSIAZKA(autor_id, ksiazka_id) VALUES (11, 14);
INSERT INTO AUTOR_KSIAZKA(autor_id, ksiazka_id) VALUES (12, 15);
INSERT INTO AUTOR_KSIAZKA(autor_id, ksiazka_id) VALUES (13, 16);
INSERT INTO AUTOR_KSIAZKA(autor_id, ksiazka_id) VALUES (14, 17);
INSERT INTO AUTOR_KSIAZKA(autor_id, ksiazka_id) VALUES (15, 18);
INSERT INTO AUTOR_KSIAZKA(autor_id, ksiazka_id) VALUES (16, 19);
INSERT INTO AUTOR_KSIAZKA(autor_id, ksiazka_id) VALUES (17, 20);
INSERT INTO AUTOR_KSIAZKA(autor_id, ksiazka_id) VALUES (18, 21);
INSERT INTO AUTOR_KSIAZKA(autor_id, ksiazka_id) VALUES (19, 22);
INSERT INTO AUTOR_KSIAZKA(autor_id, ksiazka_id) VALUES (20, 23);
INSERT INTO AUTOR_KSIAZKA(autor_id, ksiazka_id) VALUES (21, 24);
INSERT INTO AUTOR_KSIAZKA(autor_id, ksiazka_id) VALUES (22, 25);
INSERT INTO AUTOR_KSIAZKA(autor_id, ksiazka_id) VALUES (23, 26);
INSERT INTO AUTOR_KSIAZKA(autor_id, ksiazka_id) VALUES (24, 27);

INSERT INTO OSOBA(imie, nazwisko, data_urodzenia, plec, telefon, email, haslo) VALUES ('Anna', 'Nowak', to_date('01.09.1983', 'DD.MM.YYYY'), 'kobieta', '+48859559675', 'anowak@wp.pl', 'haslo123');
INSERT INTO OSOBA(imie, nazwisko, data_urodzenia, plec, telefon, email, haslo) VALUES ('Maciej', 'Kowalski', to_date('20.01.1991', 'DD.MM.YYYY'), 'mężczyzna', '+48607866795', 'maciejk@gmail.com', 'haslo123');
INSERT INTO OSOBA(imie, nazwisko, data_urodzenia, plec, telefon, email, haslo) VALUES ('Grzegorz', 'Zieliński', to_date('12.04.1988', 'DD.MM.YYYY'), 'mężczyzna', '+48655058372', 'grzegorz123@gmail.com', 'haslo123');
INSERT INTO OSOBA(imie, nazwisko, data_urodzenia, plec, telefon, email, haslo) VALUES ('Kamil', 'Szymański', to_date('03.07.1993', 'DD.MM.YYYY'), 'mężczyzna', '+48944981148', 'kszym@wp.pl', 'haslo123');
INSERT INTO OSOBA(imie, nazwisko, data_urodzenia, plec, telefon, email, haslo) VALUES ('Magdalena', 'Jankowska', to_date('21.02.1984', 'DD.MM.YYYY'), 'kobieta', '+48899521865', 'magda009@gmail.com', 'haslo123');
INSERT INTO OSOBA(imie, nazwisko, data_urodzenia, plec, telefon, email, haslo) VALUES ('Wiktoria', 'Nowicka', to_date('29.11.1994', 'DD.MM.YYYY'), 'kobieta', '+48344334783', 'wiktorian@gmail.com', 'haslo123');
INSERT INTO OSOBA(imie, nazwisko, data_urodzenia, plec, telefon, email, haslo) VALUES ('Piotr', 'Zawadzki', to_date('01.09.2007', 'DD.MM.YYYY'), 'mężczyzna', '+48720628132', 'zawadzki07@wp.pl', 'haslo123');

INSERT INTO CZYTELNIK(czytelnik_id, osoba_id) VALUES (2, 5);
INSERT INTO CZYTELNIK(czytelnik_id, osoba_id) VALUES (3, 6);
INSERT INTO CZYTELNIK(czytelnik_id, osoba_id) VALUES (4, 7);

INSERT INTO BIBLIOTEKARZ(bibliotekarz_id, osoba_id) VALUES (1, 1);
INSERT INTO BIBLIOTEKARZ(bibliotekarz_id, osoba_id) VALUES (2, 3);
INSERT INTO BIBLIOTEKARZ(bibliotekarz_id, osoba_id) VALUES (3, 4);

INSERT INTO ADMINISTRATOR(administrator_id, osoba_id) VALUES (1, 2);
